### ISSUE TITLE
rename repo to "How to tax Dodge"

### ISSUE THREAD

**Issue by meandavejustice** [leonar15/startup-checklist#1]

**Comment by cllivingston** [comment]
Indeed.  There's nothing in here discussing California's [minimum franchise tax of $800](https://www.ftb.ca.gov/businesses/faq/712.shtml), which applies to pretty much anything more complicated than a sole proprietorship.

**Comment by leonar15** [comment]
Thanks for the heads up. I'm investigating and adding this info to the checklist. Again, it's not meant to stand in for legal advice and I welcome feedback and edits!

**Comment by tomsaffell** [comment]
The list already includes "yearly File CA tax return", during the process of which the user will be made aware of the minimum $800 CA FTB tax. So I think you already have it covered, though you may want to note it, eg.:

> yearly File CA FTB corporate tax return (minimum $800)

**Comment by tomsaffell** [comment]
oh, and it's not due in the first year, which you may or may not want to mention..

**Comment by jamiesonbecker** [comment]
IANAL. I'm thinking about forking this excellent cheat sheet for Texas as well, which has much more favorable tax treatment for startups. (That is to say: zero, until you hit $1M, and then it tops out at 1% total at somewhere around $2M in gross sales; you can calculate it from three ways to be most advantageous to you; it's not technically an income tax, since those are outlawed in the Texas Constitution, but it is essentially the same thing.)

Delaware does include all of the most delicious taxes: income for both personal (generally not relevant), business (quite relevant and significant at scale), franchise (also relevant). However, Delaware corp's are much better at mergers than either of the other states (and, since it's the de facto standard, it's much easier to get purchased by a public company.)

For bootstrapping, another option is to file an LLC with a 2553 for taxation as an S-Corp. In some states, you then receive the benefit of charging order protection. However, in general, I feel that S-corps are just the best option for bootstrapping all around, although you may want to file an LLC for your IP and lease the IP to your operating S-corp.

Also, there is a legal term *nexus* that comes into play when you "do business" in another state. Each state views this differently: almost always, you have nexus when you incorporate in that state, hire people in that state, sell something in that state, or even just visit tradeshows in that state (depends, and this one is very contestable.) If you have nexus, you now have to comply with all of those state laws: income tax (both apportioned business income tax for that state: in other words, you have to pay income tax on income that was derived from sales in that state, income tax (personal) for people who work there, payroll taxes for people who work there, sales tax, etc. You'll also have to file as a foreign corp in that state. All that seed money you just raised is dripping away, right?

If this makes your head spin, that's not uncommon :) Just remember that most lawyers and accountants are not nearly as well versed in these matters as they claim, so really seek out good counsel who does have great expertise in all of these things.
